
POST http://localhost:3000/token HTTP/1.1
Content-Type: application/json
Bearer: pk_test_Jasd34dfdsds3A

{
    "card_number": 4539148803436467,
    "cvv": 123,
    "expiration_month": "12",
    "expiration_year": "2023",
    "email": "dmasgoferreyra@gmail.com"
}

###
POST http://localhost:3000/cardData HTTP/1.1
Content-Type: application/json

{
    "token": "gEWAm9pqzPlgV2SU"
}