apiVersion: v1
kind: Service
metadata:
  name: prueba-kube-service-NP
  labels:
    name: prueba-kube-deploy
    app: prueba-kube-app
spec:
  type: NodePort
  selector:
    app: prueba-kube-app
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 30072